include:
  - project: 'devops/ci-templates'
    file: '/rules/changes.gitlab-ci.yml'
  - project: 'devops/ci-templates'
    file: '/build/java.build.gitlab-ci.yml'
  - project: 'devops/ci-templates'
    file: '/deploy/java.deploy.gitlab-ci.yml'

deploy:
  extends:
    - .build
    - .java_changes
  script:
   - mvn deploy -DskipTests
